### ISSUE TITLE
How to add new roles

### ISSUE THREAD

**Issue by butterboy265** [sb2nov/resume#52]
I want to add a new role to my existing work place (i.e Engineer from 2016-2023, Program Manager from 2023-Present) how would I do that?

**Comment by dhanushm360** [comment]
Hi, did you find out how to do this?

**Comment by edoardottt** [comment]
follow. I admit it would be useful

**Comment by butterboy265** [comment]
I was able to figure it out (I just created my own function in order to do so). I'll paste it here:

\newcommand{\resumeNewRole}[2]{
 \vspace{-2pt}\item
    \begin{tabular*}{0.97\textwidth}[t]{l@{\extracolsep{\fill}}r}
     \textit{\small#1} & \textit{\small #2} \\
    \end{tabular*}\vspace{-7pt}
}

Just add this in the "custom commands" section, it works perfectly

**Comment by edoardottt** [comment]
thanks @butterboy265, appreciated!

**Comment by erdembilgin** [comment]
Hi @butterboy265, thanks for the info! 

I just have a small question. I want to remove the bullet point that comes in front of my second role. Otherwise it looks like this;
<img width="523" alt="Ekran Resmi 2024-01-04 18 54 50" src="https://github.com/sb2nov/resume/assets/71133722/5045dfbb-5b45-41e2-938a-86f14727fa8d">

I wanted to keep the bullet points only in front of the company names. How can I do that?

**Comment by franktsai127** [comment]
@erdembilgin you can try this, update your `resumeNewRole `:

```
\newcommand{\resumeNewRole}[2]{%
\vspace{-2pt}
\noindent
\begin{tabular*}{0.97\textwidth}[t]{@{}l@{\extracolsep{\fill}}r@{}}
\textit{\small#1} & \textit{\small #2} \\
\end{tabular*}%
\vspace{-7pt}
}
```

**Comment by sb2nov** [comment]
Other option is just uncommenting https://github.com/sb2nov/resume/blob/master/sourabh_bajaj_resume.tex#L128...L133 should just work for you.
